TYPO3:
  TYPO3CR:
    Search:
      elasticSearch:
        indexName: typo3cr_testing
        log:
          backendOptions:
            fileBackend:
              logFileURL: '%FLOW_PATH_DATA%Logs/ElasticSearch_Testing.log'
              severityThreshold: '%LOG_DEBUG%'
      realtimeIndexing:
        enabled: false